### ISSUE TITLE
problem with colors of the channel program

### ISSUE THREAD

**Issue by Unkash** [davidmuma/EPG_dobleM#11]
Hi all

I'm having a issue with programs, I can't watch the colors, just code

I'm using jellyfin

![IMG_20240521_131149](https://github.com/davidmuma/EPG_dobleM/assets/79589018/3f865814-6fb8-4d4b-aa24-6e526999259d)
![IMG_20240521_131532](https://github.com/davidmuma/EPG_dobleM/assets/79589018/33edf083-2879-4150-a79b-7b6beefcb9f3)

**Comment by davidmuma** [comment]
Para Jellyfin usa esta url:
https://raw.githubusercontent.com/davidmuma/EPG_dobleM/master/guiatv_light.xml.gz

**Comment by Unkash** [comment]
Gracias El 1 jul. 2024 13:31, David ***@***.***> escribió:
Para Jellyfin usa esta url:
https://raw.githubusercontent.com/davidmuma/EPG_dobleM/master/guiatv_light.xml.gz
