### ISSUE TITLE
No sé que ocurre, pero la programación ya no coincide

### ISSUE THREAD

**Issue by pepelecho** [davidmuma/EPG_dobleM#18]
La programación no coincide en absoluto con la oficial. Literalmente no sé de donde está sacando los programas porque no coincide ni uno con los oficiales

**Comment by davidmuma** [comment]
Es un problema con la web de Movistar

**Comment by pepelecho** [comment]
> Movistar ha cambiado su web, y ya debería de estar solucionado. De todas formas tampoco tengo obligación alguna ni de solucionarlo ni de darte explicaciones, y menos con esos modos

Amigo, yo no te hablé de malas formas. Siento si se interpretó así. No era mi intención ofenderle si no hacerle saber que no funcionaba desde hace unos días y antes sí. Tranquilo. Solo es que me venía bien está guía.

**Comment by hijuuijj** [comment]
> La programación no coincide en absoluto con la oficial. Literalmente no sé de donde está sacando los programas porque no coincide ni uno con los oficiales

Un poco de agradecimiento no vendría mal, considerando que esto lo hace gratis.

**Comment by pepelecho** [comment]
> > La programación no coincide en absoluto con la oficial. Literalmente no sé de donde está sacando los programas porque no coincide ni uno con los oficiales
> 
> Un poco de agradecimiento no vendría mal, considerando que esto lo hace gratis.

Claro, y yo se lo agradezco. Creo que se me malinterpretó el tono, es lo que tienen os mensajes. Solo era meramente informativo. De verdad mi intención no era ofender.

**Comment by davidmuma** [comment]
Todo vuelve a funcionar, cierro el issue
