### ISSUE TITLE
Horas canales MTV

### ISSUE THREAD

**Issue by smeagol152** [davidmuma/EPG_dobleM#2]
Hola David!

Enhorabuena por la EPG! Muy completa. Tengo algunas dudas con canales como MTV Club, MTV Hits o MTV 90. Al parecer se saca de alguna fuente que lleva una hora menos. ¿Se podría adaptar a la hora española?

Gracias

**Comment by davidmuma** [comment]
Muchas gracias, lo revisaré a ver si puedo solucionarlo
