### ISSUE TITLE
CNN en Español

### ISSUE THREAD

**Issue by hijuuijj** [davidmuma/EPG_dobleM#24]
Hola David. Podrías añadir la guía para CNN en español? no sé si esto te puede servir: https://www.tvpassport.com/tv-listings/stations/cnn-espanol/2096
Hace poco sacaron el canal para Samsung. Si no lo tienes, te puedo pasar el link.
Gracias.

**Comment by davidmuma** [comment]
Añadido canal CCN en español a la EPG

**Comment by hijuuijj** [comment]
Toma ya. Gracias David.
