### ISSUE TITLE
Problemas con la letra "ñ" y los acentos

### ISSUE THREAD

**Issue by arakuso** [davidmuma/EPG_dobleM#3]
Buenas, antes que nada agradecer tu trabajo, me a servido de mucho.
Tengo problemas a la hora de añadir la EPG con canales que tienen acentos o la letra Ñ
Estoy utilizando kodi con el cliente PVR " IPTV simple client" y no consigo que me visualice la información de los canales con caracteres propios del idioma Español.
Un ejemplo es M+ Acción o M+ Cine Español entre otros.
Sabes si el problema está en el cliente PVR que estoy utilizando? No consigo dar con la solución.
Gracias!!

**Comment by davidmuma** [comment]
Buenas, mucha gente usa mi EPG en KODI con ese addon y no tiene problemas, comprueba la configuración regional y de idioma de KODI.
Si estás utilizando una lista de canales es necesario que el nombre de los canales coincida con el nombre que aparece en mi EPG.

**Comment by arakuso** [comment]
Gracias por responder David, he comprobado la configuración regional y el idioma 20 veces, lo único que no tengo claro es la configuración del conjunto de caracteres en la misma configuración regional que lo tengo por defecto pero que tampoco noto ninguna diferencia si lo cambio. Las opciones mas cercanas son "Central Europe (ISO o WINDOWS)" o "Western Europe (ISO o WINDOWS)".
El resto de configuraciones tanto idioma como teclado están en Español.
Estoy utilizando kodi nexus para android.
Respecto a la coincidencia, lo entiendo perfectamente, de hecho, llevo varios días para hacer un archivo m3u a la carta ya que quien me entrega el archivo es de lo mas chapucero que he visto, al igual que la epg, nada que ver con la tuya.
Esta claro que el problema tiene que ver con acentos y la Ñ, son los únicos canales que no consigo visualizar la información.
Te muestro un ejemplo del archivo m3u por si algo está mal, ya que no soy experto en esto.

#EXTM3U
#EXTINF:-1 tvg-name="LA 1"tvg-id="LA 1"tvg-logo=""group-title="ES   MOVISTAR+",LA 1
http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.ts  (Funciona bien)

#EXTINF:-1 tvg-name="M+ ACCIÓN"tvg-id="M+ ACCIÓN"tvg-logo=""group-title="ES   MOVISTAR+",M+ ACCIÓN
http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.ts  (Funciona mal)

Alguna idea?

Gracias.

**Comment by arakuso** [comment]
Hola David, dices que mucha gente utiliza ese addon y no tiene problemas, podrías probar tu mismo lo que te estoy consultando?
He probado en dos dispositivos diferentes (Kodi nexus para android) y en los dos me surge el mismo problema.
Me he puesto en contacto con el desarrollador de Iptv simple client para ver cual puede ser la causa, estoy a la espera de que me conteste. Por si te interesa https://github.com/kodi-pvr/pvr.iptvsimple/issues/767

Gracias.

**Comment by arakuso** [comment]
Bueno, parece ser que di con la solución. Según el desarrollador de IPTV simple client la aplicación debería dar por validos los nombres de canal tanto en mayúsculas como minúsculas. Esa opción que tiene el addon funciona muy bien con los canales que como dije en un principio no contienen acentos o la letra Ñ, pero no funciona en el caso de caracteres. 
Madre mía, 2 días loco por algo tan simple...
Se lo comentare al desarrollador para que lo tenga en cuenta.

Gracias por nada.

**Comment by davidmuma** [comment]
Ok, cierro
