### ISSUE TITLE
Mas canales

### ISSUE THREAD

**Issue by davidamalla** [davidmuma/EPG_dobleM#4]
Hola te agradezco mucho el aporte de epg
Es posible añadir canales pluto o rakuten??
Alguno de pluto hay y de rakuten pero no funcionan 
Gracias

**Comment by davidmuma** [comment]
Para esos canales mejor usar otras EPGs, no puedo meter muchos canales porque el peso de los xmls ya es grande y en algunas aplicaciones puede dar problemas
