### ISSUE TITLE
Añadir sufijo HD 1080

### ISSUE THREAD

**Issue by argimir** [davidmuma/EPG_dobleM#5]
Sé que es imposible contemplar todas las opciones, pero si pudieras añadir la terminación "HD 1080" sería una maravilla, porque muchos proveedores de IPTV la utilizan. Por ejemplo:

<channel id="Antena 3 HD">
    <display-name lang="es">Antena 3</display-name>
    <display-name lang="es">Antena 3.</display-name>
    <display-name lang="es">Antena 3 SD</display-name>
    <display-name lang="es">Antena 3 HD</display-name>
    <display-name lang="es">Antena 3 FHD</display-name>
    <display-name lang="es">Antena 3 UHD</display-name>
    <display-name lang="es">Antena 3 720</display-name>
    <display-name lang="es">Antena 3 1080</display-name>
    **<display-name lang="es">Antena 3 HD 1080</display-name>**
     <icon src="https://raw.githubusercontent.com/davidmuma/picons_dobleM/master/icon/Antena%203%20HD.png" />

**Comment by davidmuma** [comment]
Ya hay suficientes sufijos, si mas gente lo demanda haré el cambio
