### ISSUE TITLE
Algunos epg no funcionan

### ISSUE THREAD

**Issue by davidamalla** [davidmuma/EPG_dobleM#6]
Hola gracias por tu trabajo
Desde hace 1 dia
Algunos epg no funcionan
Todos los de runtime
Y alguno mas como
Sol musica ,djazz,naturetime,cine feel good,verdi tv,escapa tv,vivir con perros y gatos

**Comment by davidmuma** [comment]
Corregidos todos esos canales

**Comment by davidmuma** [comment]
El canal Film & Co funciona perfectamente, por favor, cerciórate antes de abrir otro issue

**Comment by Alfomso51** [comment]
hola hay algunos canales que la epg no funciona, como la resistencia 24h, hollybood, y paramount
