### ISSUE TITLE
algunos epg no funcionan 

### ISSUE THREAD

**Issue by Alfomso51** [davidmuma/EPG_dobleM#7]
hola perdon por abrir otra vez este comentario pero hay algunos epg que no funcionann, como la resistencis 24h, hollybood, psramount y alguno mas que no recuerdo

**Comment by neoalarrode** [comment]
Como los de atresplayer, que cargan algún dato muy de vez en cuando

**Comment by davidmuma** [comment]
> hola perdon por abrir otra vez este comentario pero hay algunos epg que no funcionann, como la resistencis 24h, hollybood, psramount y alguno mas que no recuerdo

Todos los que has mencionado siempre han funcionado y siguen funcionando. Por favor comprueba el xml antes de abrir otro issue

**Comment by davidmuma** [comment]
> Como los de atresplayer, que cargan algún dato muy de vez en cuando

Estos canales son difíciles de capturar, y solo suelen tener la información de un par de diás

**Comment by davidmuma** [comment]
Cierro
